<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9mu6LKJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9mu6LKJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9mu6LKJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9mu6LKJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9mu6LKJ\App_KernelDevDebugContainer([
    'container.build_hash' => '9mu6LKJ',
    'container.build_id' => '6308da3a',
    'container.build_time' => 1615568626,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9mu6LKJ');
